apiVersion: app/v1
kind: Deployement
metadata:
  name: endocode
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: endo-code1
spec:
  containers:
  - name: endo-code1
    image: safeely/endo-code1_web
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred
